# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa11f0a9999974e8042a1d5c27071613ef55ef5269faa0da8324f5a251c7cea786fc42965debc3008aed347fe814b170a5628e7973a5aca0fbdbf37cdfe75335

test:
  secret_key_base: 2517acccd6497da78e88e717c2ef28758109a0cbdc5b22985a35b32d28a49378be5902604178c16a77b014e4667d46bc063b7ee9fdb8cbb4ea58ac1391566167

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
